source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "just-the-docs", "0.12.0"
gem "jekyll-sass-converter", "~> 3.1"

gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-include-cache", "~> 0.2"

gem "webrick", "~> 1.9"
